### ISSUE TITLE
Implement Basic Java Setup

### ISSUE THREAD

**Issue by astrick3** [ahundt/robone#11]
To get the robot into the FRI mode so that the plugin can talk to the arm, we have to write a small java program that does this in the KUKA Sunrise framework. 

This will run on the kuka box as a sunrise "Application", C++ code in issues #12 and #13 depend on this issue, and will be on a separate computer running the simulation. 

 - [x] Start arm up and initialize configuration
 - [x] Initialize FRI mode
 - [ ] Possibly incorporate debug logs?
 - [x] Communication with FRI plugin over FRI packets to C++

We may want to sync up with the CAMP group, particularly Christoph Graumann [add email] to use some of their debugging tools since they are entirely using Java.

**Comment by ahundt** [comment]
Testing was successful, I was able to receive messages over C++ with the application Alex created
