### ISSUE TITLE
Implement and test read arm state over Fast Robot Interface (FRI)

### ISSUE THREAD

**Issue by astrick3** [ahundt/robone#12]
Depends on #11

**Comment by ahundt** [comment]
Test of the basic synchronous version was successful, now need to test async version.

**Comment by ahundt** [comment]
We are able to read arm state successfully over the FRI connection. While there are currently quality issues those will be addressed as part of  #13 because high connection quality is required to send commands.

**Comment by ahundt** [comment]
This issue was moved to ahundt/grl#12
