### ISSUE TITLE
Move real KUKA arm along simple series of points (joint and/or cartesian space)

### ISSUE THREAD

**Issue by astrick3** [ahundt/robone#15]
If possible @ahundt recommends using copellia robotics path files as an intermediate format.

- http://www.coppeliarobotics.com/helpFiles/en/pathImportExport.htm
 
Will be part of the C++ Plugin. This will be the component that synchronizes the robot to the simulation. The simulation needs to be updated with the real location of the robot, and then the simulation should run to the next step. When the simulation moves to the next step we should do some error checking, then send the joint angles as a command to the robot. 

We may also need to incorporate interpolation across time because the robot needs very fast feedback that we can't keep up with. This means the simulation will up date every approx 20ms, but we need to update the robot every 1ms, for example.

 - [x] create a plugin with a loop that reads simulation state off the simulation
 - [x] add plugin (synthetic) updates of the simulation with new synthetic state from the arm
 - [x] load plugin in vrep and test that the data is being read/written
 - [x] create loop that feeds new position updates to the simulation and new simulation updates to the real arm

**Comment by ahundt** [comment]
Commit 859a6bf is also related to this issue

**Comment by ahundt** [comment]
I was able to compile shahriar's code on OS X into a plugin and put it into v-rep, but I ran into problems and [posted a question on the V-rep forum](http://www.forum.coppeliarobotics.com/viewtopic.php?f=9&t=3151).

**Comment by ahundt** [comment]
commit https://github.com/ahundt/robone/commit/903b3d3940e7c692bfa1bde91e1e4c1374e3df5b also relates to this issue
