### ISSUE TITLE
Java ascii cutfile to vrep path file

### ISSUE THREAD

**Issue by astrick3** [ahundt/robone#17]
If we go with substantial v-rep integration we should consider the paths v-rep supplies itself:

Originally called:
Implement ascii parsing and conversion to format amenable to sending to planner or arm as commands.

**Comment by ahundt** [comment]
The conversion library is in roboneprivate, though there isn't an executable for it only test files. Creating an executable should be fairly simple but we don't have anything we need to convert at the moment.
