### ISSUE TITLE
Project plan document due 2/20

### ISSUE THREAD

**Issue by ahundt** [ahundt/robone#44]
The project plan document is here:
https://docs.google.com/document/d/1HId74qZUNspPID6MlJ2QITOiNdjpolJ68U2dXULqIpI/edit?usp=sharing

**Comment by astrick3** [comment]
Is the weight of the leg enough to keep the bone relatively still or do we need to fix the leg in some way?

**Comment by ahundt** [comment]
This issue was moved to ahundt/grl#44
